bin: akbuild: Rename clang to compiler
Akbuild support GCC

diff --git a/bin/akbuild b/bin/akbuild
--- a/bin/akbuild
+++ b/bin/akbuild
@@ -1,5 +1,5 @@
 #!/bin/bash
-AKBUILD_VERSION="2.14"
+AKBUILD_VERSION="2.15"
 
 # Default configuration values
 DEF_CONFIGFILE=$HOME/.akbuild_config
@@ -24,11 +24,11 @@ DEF_AKBUILD_KERNELNAME="QuicksilveRV2"
 DEF_AKBUILD_KDEPTH1=true                                           # Clone kernel with --depth=1
 
 # Clang
-DEF_AKBUILD_PREINSTALLED_CLANG=false
-DEF_AKBUILD_CLANGURL="https://github.com/kdrag0n/proton-clang.git"
-DEF_AKBUILD_CLANGBRANCH="master"
-DEF_AKBUILD_CLANG=""                                               # Custom path to clang, clang from AKBUILD_PATH will be used, if not selected. Example: AKBUILD_CLANG="/home/sarisan/proton-clang"
-DEF_AKBUILD_CLANGBIN="bin"                                         # You can set custom path for binaries, it's needed when you are using AOSP clang or similar clang repository. Example: AKBUILD_CLANGBIN="clang-r353983c1/bin"
+DEF_AKBUILD_PREINSTALLED_COMPILER=false
+DEF_AKBUILD_COMPILERURL="https://github.com/kdrag0n/proton-clang.git"
+DEF_AKBUILD_COMPILERBRANCH="master"
+DEF_AKBUILD_COMPILER=""                                            # Custom path to compiler, compiler from AKBUILD_PATH will be used, if not selected. Example: AKBUILD_COMPILER="/home/sarisan/proton-clang"
+DEF_AKBUILD_COMPILERBIN="bin"                                      # You can set custom path for binaries, it's needed when you are using AOSP clang or similar compiler repository. Example: AKBUILD_COMPILERBIN="clang-r353983c1/bin"
 
 # Device
 DEF_AKBUILD_ANYKERNEL=true
@@ -44,7 +44,7 @@ GDFC="\033[0;32m"     # Default green font
 RDFC="\033[0;31m"     # Default red font
 
 # Default config
-AKBUILD_CONFIG="# Android kernel build configuration\nAKBUILD_PATH=\"$PWD\"\nAKBUILD_JOBS=\"$DEF_AKBUILD_JOBS\"\nAKBUILD_USERNAME=\"$DEF_AKBUILD_USERNAME\"\nAKBUILD_HOSTNAME=\"$DEF_AKBUILD_HOSTNAME\"\nAKBUILD_ARCH=\"$DEF_AKBUILD_ARCH\"\nAKBUILD_CC=\"$DEF_AKBUILD_CC\"\nAKBUILD_OPTIONS=\"$DEF_AKBUILD_OPTIONS\"\nAKBUILD_DEFCONFIG=\"$DEF_AKBUILD_DEFCONFIG\"\nAKBUILD_OUTPUTFILE=\"$DEF_AKBUILD_OUTPUTFILE\"\nAKBUILD_DTBO=$DEF_AKBUILD_DTBO\nAKBUILD_CCACHE=$DEF_AKBUILD_CCACHE\nAKBUILD_CCACHE_DIR=\"$DEF_AKBUILD_CCACHE_DIR\"\n\n# Kernel\nAKBUILD_KERNELURL=\"$DEF_AKBUILD_KERNELURL\"\nAKBUILD_KERNELBRANCH=\"$DEF_AKBUILD_KERNELBRANCH\"\nAKBUILD_KERNELNAME=\"$DEF_AKBUILD_KERNELNAME\"\nAKBUILD_KDEPTH1=$DEF_AKBUILD_KDEPTH1\n\n# Clang\nAKBUILD_PREINSTALLED_CLANG=$DEF_AKBUILD_PREINSTALLED_CLANG\nAKBUILD_CLANGURL=\"$DEF_AKBUILD_CLANGURL\"\nAKBUILD_CLANGBRANCH=\"$DEF_AKBUILD_CLANGBRANCH\"\nAKBUILD_CLANG=\"$DEF_AKBUILD_CLANG\"\nAKBUILD_CLANGBIN=\"$DEF_AKBUILD_CLANGBIN\"\n\n# Device\nAKBUILD_ANYKERNEL=$DEF_AKBUILD_ANYKERNEL\nAKBUILD_ANYKERNELURL=\"$DEF_AKBUILD_ANYKERNELURL\"\nAKBUILD_ANYKERNELBRANCH=\"$DEF_AKBUILD_ANYKERNELBRANCH\"\nAKBUILD_DEVICENAME=\"$DEF_AKBUILD_DEVICENAME\""
+AKBUILD_CONFIG="# Android kernel build configuration\nAKBUILD_PATH=\"$PWD\"\nAKBUILD_JOBS=\"$DEF_AKBUILD_JOBS\"\nAKBUILD_USERNAME=\"$DEF_AKBUILD_USERNAME\"\nAKBUILD_HOSTNAME=\"$DEF_AKBUILD_HOSTNAME\"\nAKBUILD_ARCH=\"$DEF_AKBUILD_ARCH\"\nAKBUILD_CC=\"$DEF_AKBUILD_CC\"\nAKBUILD_OPTIONS=\"$DEF_AKBUILD_OPTIONS\"\nAKBUILD_DEFCONFIG=\"$DEF_AKBUILD_DEFCONFIG\"\nAKBUILD_OUTPUTFILE=\"$DEF_AKBUILD_OUTPUTFILE\"\nAKBUILD_DTBO=$DEF_AKBUILD_DTBO\nAKBUILD_CCACHE=$DEF_AKBUILD_CCACHE\nAKBUILD_CCACHE_DIR=\"$DEF_AKBUILD_CCACHE_DIR\"\n\n# Kernel\nAKBUILD_KERNELURL=\"$DEF_AKBUILD_KERNELURL\"\nAKBUILD_KERNELBRANCH=\"$DEF_AKBUILD_KERNELBRANCH\"\nAKBUILD_KERNELNAME=\"$DEF_AKBUILD_KERNELNAME\"\nAKBUILD_KDEPTH1=$DEF_AKBUILD_KDEPTH1\n\n# Clang\nAKBUILD_PREINSTALLED_COMPILER=$DEF_AKBUILD_PREINSTALLED_COMPILER\nAKBUILD_COMPILERURL=\"$DEF_AKBUILD_COMPILERURL\"\nAKBUILD_COMPILERBRANCH=\"$DEF_AKBUILD_COMPILERBRANCH\"\nAKBUILD_COMPILER=\"$DEF_AKBUILD_COMPILER\"\nAKBUILD_COMPILERBIN=\"$DEF_AKBUILD_COMPILERBIN\"\n\n# Device\nAKBUILD_ANYKERNEL=$DEF_AKBUILD_ANYKERNEL\nAKBUILD_ANYKERNELURL=\"$DEF_AKBUILD_ANYKERNELURL\"\nAKBUILD_ANYKERNELBRANCH=\"$DEF_AKBUILD_ANYKERNELBRANCH\"\nAKBUILD_DEVICENAME=\"$DEF_AKBUILD_DEVICENAME\""
 
 
 AKCONFIGFILE=$DEF_CONFIGFILE
@@ -89,17 +89,17 @@ AKDEPTH="--depth=1"
 else
 AKDEPTH=""
 fi
-if [ $AKBUILD_PREINSTALLED_CLANG = true ]; then
-AKCLANG="$AKBUILD_PATH"
+if [ $AKBUILD_PREINSTALLED_COMPILER = true ]; then
+AKCOMPILER="$AKBUILD_PATH"
 AKCS="Preinstalled"
 else
-if [ $AKBUILD_CLANG ]; then
-AKCLANG="$AKBUILD_CLANG"
+if [ $AKBUILD_COMPILER ]; then
+AKCOMPILER="$AKBUILD_COMPILER"
 else
-AKCLANG="$AKBUILD_PATH/clang"
+AKCOMPILER="$AKBUILD_PATH/compiler"
 fi
-export PATH="$AKCLANG/$AKBUILD_CLANGBIN:$PATH"
-AKCS="$AKCLANG/$AKBUILD_CLANGBIN"
+export PATH="$AKCOMPILER/$AKBUILD_COMPILERBIN:$PATH"
+AKCS="$AKCOMPILER/$AKBUILD_COMPILERBIN"
 fi
 if [ $AKBUILD_ANYKERNEL = true ]; then
 AKANYKERNEL="Enabled"
@@ -107,7 +107,7 @@ else
 AKANYKERNEL="Disabled"
 fi
 AKKERNELS="$AKDEPTH $AKBUILD_KERNELURL -b $AKBUILD_KERNELBRANCH $AKBUILD_PATH/kernel"
-AKCLANGS="--depth=1 $AKBUILD_CLANGURL -b $AKBUILD_CLANGBRANCH $AKCLANG"
+AKCOMPILERS="--depth=1 $AKBUILD_COMPILERURL -b $AKBUILD_COMPILERBRANCH $AKCOMPILER"
 
 if [ "$1" = "version" ] || [ "$1" = "help" ] || [ "$1" = "config" ] || [ "$1" = "clone" ] || [ "$1" = "pull" ] || [ "$1" = "build" ] || [ "$1" = "clean" ]; then
 
@@ -116,12 +116,12 @@ echo -e "akbuild version $AKBUILD_VERSION"
 fi
 
 if [ "$1" = "help" ]; then
-echo -e "\tversion\t\tShow akbuild version\n\thelp\t\tShow this\n\tconfig\t\tActions with configuration files\n\tclone\t\tClone the kernel and the clang\n\tpull\t\tUpdate the kernel and the clang with$BDFC git pull$DFC if possible\n\tbuild\t\tStart building the kernel\n\tclean\t\tRemove output folder\n\n\takbuild config\n\t\tShow current configuration\n\n\takbuild config [-c <filename>] [-d] [-r] [-r <filename>]\n\n\t\t-c <filename>, --custom <filename>\n\t\t\tLoad configuration from file\n\n\t\t-d, --default\n\t\t\tLoad configuration from default file\n\n\t\t-r, --regenerate\n\t\t\tRegenerate default configuration file\n\n\t\t-r <filename>, --regenerate <filename>\n\t\t\tRegenerate configuration to file\n\n\takbuild clone/pull\n\t\tClone/Pull the kernel and the clang\n\n\takbuild clone/pull kernel\n\t\tClone/Pull only the kernel\n\n\takbuild clone/pull clang\n\t\tClone/Pull only the clang"
+echo -e "\tversion\t\tShow akbuild version\n\thelp\t\tShow this\n\tconfig\t\tActions with configuration files\n\tclone\t\tClone the kernel and the compiler\n\tpull\t\tUpdate the kernel and the compiler with$BDFC git pull$DFC if possible\n\tbuild\t\tStart building the kernel\n\tclean\t\tRemove output folder\n\n\takbuild config\n\t\tShow current configuration\n\n\takbuild config [-c <filename>] [-d] [-r] [-r <filename>]\n\n\t\t-c <filename>, --custom <filename>\n\t\t\tLoad configuration from file\n\n\t\t-d, --default\n\t\t\tLoad configuration from default file\n\n\t\t-r, --regenerate\n\t\t\tRegenerate default configuration file\n\n\t\t-r <filename>, --regenerate <filename>\n\t\t\tRegenerate configuration to file\n\n\takbuild clone/pull\n\t\tClone/Pull the kernel and the compiler\n\n\takbuild clone/pull kernel\n\t\tClone/Pull only the kernel\n\n\takbuild clone/pull compiler\n\t\tClone/Pull only the compiler"
 fi
 
 if [ "$1" = "config" ] && [ "$2" = "" ] || [ "$2" = "-c" ] || [ "$2" = "--custom" ] || [ "$2" = "-d" ] || [ "$2" = "--default" ] || [ "$2" = "-r" ] || [ "$2" = "--regenerate" ]; then
 if [ "$1" = "config" ] && [ "$2" = "" ]; then
-echo -e "Work path: $AKBUILD_PATH\nJobs: $AKBUILD_JOBS\nBuilder: $KBUILD_BUILD_USER@$KBUILD_BUILD_HOST\nKernel image: $AKBUILD_OUTPUTFILE\nBuild dtbo.img: $AKDTBOS\nCcache: $AKCCS\nKernel: $AKBUILD_KERNELNAME\nClang binaries: $AKCS\nAnyKernel: $AKANYKERNEL\nDevice: $AKBUILD_DEVICENAME"
+echo -e "Work path: $AKBUILD_PATH\nJobs: $AKBUILD_JOBS\nBuilder: $KBUILD_BUILD_USER@$KBUILD_BUILD_HOST\nKernel image: $AKBUILD_OUTPUTFILE\nBuild dtbo.img: $AKDTBOS\nCcache: $AKCCS\nKernel: $AKBUILD_KERNELNAME\nCompiler binaries: $AKCS\nAnyKernel: $AKANYKERNEL\nDevice: $AKBUILD_DEVICENAME"
 fi
 if [ "$1" = "config" ] && [ "$2" = "-c" ] || [ "$2" = "--custom" ] && [ "$3" ]; then
 if [ -f $3 ]; then
@@ -158,7 +158,7 @@ echo -e "Invalid argument '$2'"
 fi
 fi
 
-if [ "$1" = "clone" ] && [ "$2" = "" ] || [ "$2" = "kernel" ] || [ "$2" = "clang" ]; then
+if [ "$1" = "clone" ] && [ "$2" = "" ] || [ "$2" = "kernel" ] || [ "$2" = "compiler" ]; then
 if [ "$1" = "clone" ] && [ "$2" = "" ]; then
 if [ -d $AKBUILD_PATH/kernel ]; then
 echo -e "The kernel has already been cloned"
@@ -167,15 +167,15 @@ if ! git clone $AKKERNELS; then
 echo -e "Error cloning the kernel"
 fi
 fi
-if [ -d $AKCLANG ]; then
-if [ $AKBUILD_CLANG ]; then
-echo -e "You are using clang from external path"
+if [ -d $AKCOMPILER ]; then
+if [ $AKBUILD_COMPILER ]; then
+echo -e "You are using compiler from external path"
 else
-echo -e "The clang has already been cloned"
+echo -e "The compiler has already been cloned"
 fi
 else
-if ! git clone $AKCLANGS; then
-echo -e "Error cloning the clang"
+if ! git clone $AKCOMPILERS; then
+echo -e "Error cloning the compiler"
 fi
 fi
 fi
@@ -188,16 +188,16 @@ echo -e "Error cloning the kernel"
 fi
 fi
 fi
-if [ "$1" = "clone" ] && [ "$2" = clang ]; then
-if [ -d $AKCLANG ]; then
-if [ $AKBUILD_CLANG ]; then
-echo -e "You are using the clang from external path"
+if [ "$1" = "clone" ] && [ "$2" = compiler ]; then
+if [ -d $AKCOMPILER ]; then
+if [ $AKBUILD_COMPILER ]; then
+echo -e "You are using the compiler from external path"
 else
-echo -e "The clang has already been cloned"
+echo -e "The compiler has already been cloned"
 fi
 else
-if ! git clone $AKCLANGS; then
-echo -e "Error cloning the clang"
+if ! git clone $AKCOMPILERS; then
+echo -e "Error cloning the compiler"
 fi
 fi
 fi
@@ -207,7 +207,7 @@ echo -e "Invalid argument '$2'"
 fi
 fi
 
-if [ "$1" = "pull" ] && [ "$2" = "" ] || [ "$2" = "kernel" ] || [ "$2" = "clang" ]; then
+if [ "$1" = "pull" ] && [ "$2" = "" ] || [ "$2" = "kernel" ] || [ "$2" = "compiler" ]; then
 if [ "$1" = "pull" ] && [ "$2" = "" ]; then
 if [ -d $AKBUILD_PATH/kernel ]; then
 cd $AKBUILD_PATH/kernel
@@ -217,13 +217,13 @@ fi
 else
 echo -e "The kernel is not cloned"
 fi
-if [ -d $AKCLANG ]; then
-cd $AKCLANG
+if [ -d $AKCOMPILER ]; then
+cd $AKCOMPILER
 if ! git pull; then
-echo -e "Error pulling the clang"
+echo -e "Error pulling the compiler"
 fi
 else
-echo -e "The clang is not cloned"
+echo -e "The compiler is not cloned"
 fi
 fi
 if [ "$1" = "pull" ] && [ "$2" = "kernel" ]; then
@@ -236,14 +236,14 @@ else
 echo -e "The kernel is not cloned"
 fi
 fi
-if [ "$1" = "pull" ] && [ "$2" = "clang" ]; then
-if [ -d $AKCLANG ]; then
-cd $AKCLANG
+if [ "$1" = "pull" ] && [ "$2" = "compiler" ]; then
+if [ -d $AKCOMPILER ]; then
+cd $AKCOMPILER
 if ! git pull; then
-echo -e "Error pulling the clang"
+echo -e "Error pulling the compiler"
 fi
 else
-echo -e "The clang is not cloned"
+echo -e "The compiler is not cloned"
 fi
 fi
 else
@@ -254,7 +254,7 @@ fi
 
 if [ "$1" = "build" ]; then
 if [ -d $AKBUILD_PATH/kernel ]; then
-if [ -d $AKCLANG ]; then
+if [ -d $AKCOMPILER ]; then
 if
 SECONDS=0
 cd $AKBUILD_PATH/kernel
@@ -298,7 +298,7 @@ cd $AKBUILD_PATH
 echo -e "$RDFC\nBuild failed! Something went wrong | $AKTIME$DFC"
 fi
 else
-echo -e "The clang is not cloned"
+echo -e "The compiler is not cloned"
 fi
 else
 echo -e "The kernel is not cloned"
@@ -318,4 +318,4 @@ fi
 fi
 
 mkdir -p $CACHE
-echo -e "# Android kernel build configuration\nAKBUILD_PATH=\"$AKBUILD_PATH\"\nAKBUILD_JOBS=\"$AKBUILD_JOBS\"\nAKBUILD_USERNAME=\"$AKBUILD_USERNAME\"\nAKBUILD_HOSTNAME=\"$AKBUILD_HOSTNAME\"\nAKBUILD_ARCH=\"$AKBUILD_ARCH\"\nAKBUILD_CC=\"$AKBUILD_CC\"\nAKBUILD_OPTIONS=\"$AKBUILD_OPTIONS\"\nAKBUILD_DEFCONFIG=\"$AKBUILD_DEFCONFIG\"\nAKBUILD_OUTPUTFILE=\"$AKBUILD_OUTPUTFILE\"\nAKBUILD_DTBO=$AKBUILD_DTBO\nAKBUILD_CCACHE=$AKBUILD_CCACHE\nAKBUILD_CCACHE_DIR=\"$AKBUILD_CCACHE_DIR\"\n\n# Kernel\nAKBUILD_KERNELURL=\"$AKBUILD_KERNELURL\"\nAKBUILD_KERNELBRANCH=\"$AKBUILD_KERNELBRANCH\"\nAKBUILD_KERNELNAME=\"$AKBUILD_KERNELNAME\"\nAKBUILD_KDEPTH1=$AKBUILD_KDEPTH1\n\n# Clang\nAKBUILD_PREINSTALLED_CLANG=$AKBUILD_PREINSTALLED_CLANG\nAKBUILD_CLANGURL=\"$AKBUILD_CLANGURL\"\nAKBUILD_CLANGBRANCH=\"$AKBUILD_CLANGBRANCH\"\nAKBUILD_CLANG=\"$AKBUILD_CLANG\"\nAKBUILD_CLANGBIN=\"$AKBUILD_CLANGBIN\"\n\n# Device\nAKBUILD_ANYKERNEL=$AKBUILD_ANYKERNEL\nAKBUILD_ANYKERNELURL=\"$AKBUILD_ANYKERNELURL\"\nAKBUILD_ANYKERNELBRANCH=\"$AKBUILD_ANYKERNELBRANCH\"\nAKBUILD_DEVICENAME=\"$AKBUILD_DEVICENAME\"" > $CACHECONFIGFILE
+echo -e "# Android kernel build configuration\nAKBUILD_PATH=\"$AKBUILD_PATH\"\nAKBUILD_JOBS=\"$AKBUILD_JOBS\"\nAKBUILD_USERNAME=\"$AKBUILD_USERNAME\"\nAKBUILD_HOSTNAME=\"$AKBUILD_HOSTNAME\"\nAKBUILD_ARCH=\"$AKBUILD_ARCH\"\nAKBUILD_CC=\"$AKBUILD_CC\"\nAKBUILD_OPTIONS=\"$AKBUILD_OPTIONS\"\nAKBUILD_DEFCONFIG=\"$AKBUILD_DEFCONFIG\"\nAKBUILD_OUTPUTFILE=\"$AKBUILD_OUTPUTFILE\"\nAKBUILD_DTBO=$AKBUILD_DTBO\nAKBUILD_CCACHE=$AKBUILD_CCACHE\nAKBUILD_CCACHE_DIR=\"$AKBUILD_CCACHE_DIR\"\n\n# Kernel\nAKBUILD_KERNELURL=\"$AKBUILD_KERNELURL\"\nAKBUILD_KERNELBRANCH=\"$AKBUILD_KERNELBRANCH\"\nAKBUILD_KERNELNAME=\"$AKBUILD_KERNELNAME\"\nAKBUILD_KDEPTH1=$AKBUILD_KDEPTH1\n\n# Clang\nAKBUILD_PREINSTALLED_COMPILER=$AKBUILD_PREINSTALLED_COMPILER\nAKBUILD_COMPILERURL=\"$AKBUILD_COMPILERURL\"\nAKBUILD_COMPILERBRANCH=\"$AKBUILD_COMPILERBRANCH\"\nAKBUILD_COMPILER=\"$AKBUILD_COMPILER\"\nAKBUILD_COMPILERBIN=\"$AKBUILD_COMPILERBIN\"\n\n# Device\nAKBUILD_ANYKERNEL=$AKBUILD_ANYKERNEL\nAKBUILD_ANYKERNELURL=\"$AKBUILD_ANYKERNELURL\"\nAKBUILD_ANYKERNELBRANCH=\"$AKBUILD_ANYKERNELBRANCH\"\nAKBUILD_DEVICENAME=\"$AKBUILD_DEVICENAME\"" > $CACHECONFIGFILE
