bin: cscd: Create cache dir with pid to allow multi downloading
Co-authored-by: Sakuyouuu <86886574+Sakuyouuu@users.noreply.github.com>

diff --git a/bin/cscd b/bin/cscd
--- a/bin/cscd
+++ b/bin/cscd
@@ -11,12 +11,13 @@
 
 if command -v curl &> /dev/null && command -v jq &> /dev/null && command -v sed &> /dev/null; then
 
-VERSION="CSCD v1.2"
+VERSION="CSCD v1.3"
 CONFIG=$HOME/.config/cscd
 CACHE=$HOME/.cache/cscd
+CPID_CACHE=$CACHE/$$
 
 mkdir -p $CONFIG
-mkdir -p $CACHE
+mkdir -p $CPID_CACHE
 
 if [ -f $CONFIG/cscd.conf ]; then
 . $CONFIG/cscd.conf
@@ -63,17 +64,17 @@ read -e -p "Password: " CSANKAKU_PASSWORD
 done
 
 echo "{\"login\":\"$CSANKAKU_LOGIN\",\"password\":\"$CSANKAKU_PASSWORD\"}" > $CONFIG/login.json
-curl -s -A "Chrome" -X POST -H "Content-Type: application/json" -d @$CONFIG/login.json https://capi-v2.sankakucomplex.com/auth/token -o $CACHE/login
+curl -s -A "Chrome" -X POST -H "Content-Type: application/json" -d @$CONFIG/login.json https://capi-v2.sankakucomplex.com/auth/token -o $CPID_CACHE/login
 
-if [ "$(jq -r 'map_values(tostring)|.success' $CACHE/login)" = "true" ]; then
-jq -r '.access_token' $CACHE/login | cat > $CONFIG/token
+if [ "$(jq -r 'map_values(tostring)|.success' $CPID_CACHE/login)" = "true" ]; then
+jq -r '.access_token' $CPID_CACHE/login | cat > $CONFIG/token
 echo -e "\nAuthorized successfully\n"
 else
 
-if ! [ -f $CACHE/login ]; then
+if ! [ -f $CPID_CACHE/login ]; then
 echo -e "\nError: failed to access https://capi-v2.sankakucomplex.com\n"
 else
-echo -e "\nError: $(jq -r .error $CACHE/login)\n"
+echo -e "\nError: $(jq -r .error $CPID_CACHE/login)\n"
 fi
 
 fi
@@ -128,25 +129,25 @@ fi
 echo -ne "\n\rDownloaded posts: 0"
 while ! [ $COUNT = $NUMBER ]; do
 
-curl -s -A "Chrome" -X GET -H "Authorization: Bearer $(cat $CONFIG/token)" -o $CACHE/posts "https://capi-v2.sankakucomplex.com/posts?page=$PAGE\&tags=$TAGS"
+curl -s -A "Chrome" -X GET -H "Authorization: Bearer $(cat $CONFIG/token)" -o $CPID_CACHE/posts "https://capi-v2.sankakucomplex.com/posts?page=$PAGE\&tags=$TAGS"
 
-if [ "$(cat $CACHE/posts)" = "[]" ]; then
+if [ "$(cat $CPID_CACHE/posts)" = "[]" ]; then
 break
 fi
 
-cat $CACHE/posts | jq -r '.[]|map_values(tostring)|"{\"id\":\"\(.id)\",\"rating\":\"\(.rating)\",\"sample_url\":\"\(.sample_url)\",\"preview_url\":\"\(.preview_url)\",\"file_url\":\"\(.file_url)\",\"file_size\":\"\(.file_size)\",\"file_type\":\"\(.file_type)\",\"width\":\"\(.width)\",\"height\":\"\(.height)\"}"' | sed "s|:\"s\"|:\"Safe\"|g" | sed "s|:\"q\"|:\"Questionable\"|g" | sed "s|:\"e\"|:\"Explicit\"|g" | sed "s|type\":\"image\/|type\":\"|g" | sed "s|type\":\"video\/|type\":\"|g" | cat > $CACHE/info
+cat $CPID_CACHE/posts | jq -r '.[]|map_values(tostring)|"{\"id\":\"\(.id)\",\"rating\":\"\(.rating)\",\"sample_url\":\"\(.sample_url)\",\"preview_url\":\"\(.preview_url)\",\"file_url\":\"\(.file_url)\",\"file_size\":\"\(.file_size)\",\"file_type\":\"\(.file_type)\",\"width\":\"\(.width)\",\"height\":\"\(.height)\"}"' | sed "s|:\"s\"|:\"Safe\"|g" | sed "s|:\"q\"|:\"Questionable\"|g" | sed "s|:\"e\"|:\"Explicit\"|g" | sed "s|type\":\"image\/|type\":\"|g" | sed "s|type\":\"video\/|type\":\"|g" | cat > $CPID_CACHE/info
 
-for info in $(cat $CACHE/info); do
+for info in $(cat $CPID_CACHE/info); do
 
 if [ $COUNT = $NUMBER ]; then
 break
 fi
 
 if ! [ -f "$DOWNLOAD_DIR/$(echo $info | jq -r '.file_url' | cut -d'?' -f1 | cut -d'/' -f7)" ]; then
-curl -s -A "Chrome" "$(echo $info | jq -r '.file_url')" -o $CACHE/file
+curl -s -A "Chrome" "$(echo $info | jq -r '.file_url')" -o $CPID_CACHE/file
 
-if [ -f $CACHE/file ]; then
-mv "$CACHE/file" "$DOWNLOAD_DIR/$(echo $info | jq -r '.file_url' | cut -d'?' -f1 | cut -d'/' -f7)"
+if [ -f $CPID_CACHE/file ]; then
+mv "$CPID_CACHE/file" "$DOWNLOAD_DIR/$(echo $info | jq -r '.file_url' | cut -d'?' -f1 | cut -d'/' -f7)"
 else
 NSKIP=$((NSKIP+1))
 COUNT=$((COUNT-1))
@@ -168,8 +169,8 @@ SIZE=$((SIZE))B
 fi
 
 if [ "$(echo $info | jq -r '.file_type')" = "jpeg" ] || [ "$(echo $info | jq -r '.file_type')" = "png" ]; then
-curl -s -A "Chrome" "$(echo $info | jq -r '.sample_url')" -o $CACHE/sample
-curl -s -X POST https://api.telegram.org/bot$TG_BOT_TOKEN/sendPhoto -F chat_id=$CHAT -F caption="$VERSION$(if [ $NUMBER != '-1' ]; then echo -e "\n$COUNT/$NUMBER"; fi)" -F photo="@$CACHE/sample" -F reply_markup=$(echo '{"inline_keyboard":[[{"text":"rating","url":"spid"},{"text":"widthxheight","url":"spid"}]],"inline_keyboard":[[{"text":"fsize","url":"spid"},{"text":"ftype","url":"spid"}]]}' | sed "s|rating|$(echo $info | jq -r '.rating')|g" | sed "s|width|$(echo $info | jq -r '.width')|g" | sed "s|height|$(echo $info | jq -r '.height')|g" | sed "s|fsize|$SIZE|g" | sed "s|ftype|$(echo $info | jq -r '.file_type')|g" | sed "s|spid|https://chan.sankakucomplex.com/post/show/$(echo $info | jq -r '.id')|g") | cat > /dev/null
+curl -s -A "Chrome" "$(echo $info | jq -r '.sample_url')" -o $CPID_CACHE/sample
+curl -s -X POST https://api.telegram.org/bot$TG_BOT_TOKEN/sendPhoto -F chat_id=$CHAT -F caption="$VERSION$(if [ $NUMBER != '-1' ]; then echo -e "\n$COUNT/$NUMBER"; fi)" -F photo="@$CPID_CACHE/sample" -F reply_markup=$(echo '{"inline_keyboard":[[{"text":"rating","url":"spid"},{"text":"widthxheight","url":"spid"}]],"inline_keyboard":[[{"text":"fsize","url":"spid"},{"text":"ftype","url":"spid"}]]}' | sed "s|rating|$(echo $info | jq -r '.rating')|g" | sed "s|width|$(echo $info | jq -r '.width')|g" | sed "s|height|$(echo $info | jq -r '.height')|g" | sed "s|fsize|$SIZE|g" | sed "s|ftype|$(echo $info | jq -r '.file_type')|g" | sed "s|spid|https://chan.sankakucomplex.com/post/show/$(echo $info | jq -r '.id')|g") | cat > /dev/null
 else
 if (("$(echo $info | jq -r '.file_size')"<="52428800")) && [ "$(echo $info | jq -r '.file_type')" = "mp4" ] || [ "$(echo $info | jq -r '.file_type')" = "webm" ]; then
 curl -s -X POST https://api.telegram.org/bot$TG_BOT_TOKEN/sendVideo -F chat_id=$CHAT -F caption="$VERSION$(if [ $NUMBER != '-1' ]; then echo -e "\n$COUNT/$NUMBER"; fi)" -F video="@$DOWNLOAD_DIR/$(echo $info | jq -r '.file_url' | cut -d'?' -f1 | cut -d'/' -f7)" -F reply_markup=$(echo '{"inline_keyboard":[[{"text":"rating","url":"spid"},{"text":"widthxheight","url":"spid"}]],"inline_keyboard":[[{"text":"fsize","url":"spid"},{"text":"ftype","url":"spid"}]]}' | sed "s|rating|$(echo $info | jq -r '.rating')|g" | sed "s|width|$(echo $info | jq -r '.width')|g" | sed "s|height|$(echo $info | jq -r '.height')|g" | sed "s|fsize|$SIZE|g" | sed "s|ftype|$(echo $info | jq -r '.file_type')|g" | sed "s|spid|https://chan.sankakucomplex.com/post/show/$(echo $info | jq -r '.id')|g") | cat > /dev/null
@@ -177,8 +178,8 @@ else
 if (("$(echo $info | jq -r '.file_size')"<="52428800")) && [ "$(echo $info | jq -r '.file_type')" = "gif" ]; then
 curl -s -X POST https://api.telegram.org/bot$TG_BOT_TOKEN/sendAnimation -F chat_id=$CHAT -F caption="$VERSION$(if [ $NUMBER != '-1' ]; then echo -e "\n$COUNT/$NUMBER"; fi)" -F animation="@$DOWNLOAD_DIR/$(echo $info | jq -r '.file_url' | cut -d'?' -f1 | cut -d'/' -f7)" -F reply_markup=$(echo '{"inline_keyboard":[[{"text":"rating","url":"spid"},{"text":"widthxheight","url":"spid"}]],"inline_keyboard":[[{"text":"fsize","url":"spid"},{"text":"ftype","url":"spid"}]]}' | sed "s|rating|$(echo $info | jq -r '.rating')|g" | sed "s|width|$(echo $info | jq -r '.width')|g" | sed "s|height|$(echo $info | jq -r '.height')|g" | sed "s|fsize|$SIZE|g" | sed "s|ftype|$(echo $info | jq -r '.file_type')|g" | sed "s|spid|https://chan.sankakucomplex.com/post/show/$(echo $info | jq -r '.id')|g") | cat > /dev/null
 else
-curl -s -A "Chrome" "$(echo $info | jq -r '.preview_url')" -o $CACHE/preview
-curl -s -X POST https://api.telegram.org/bot$TG_BOT_TOKEN/sendPhoto -F chat_id=$CHAT -F caption="$VERSION$(if [ $NUMBER != '-1' ]; then echo -e "\n$COUNT/$NUMBER"; fi)" -F photo="@$CACHE/preview" -F reply_markup=$(echo '{"inline_keyboard":[[{"text":"rating","url":"spid"},{"text":"widthxheight","url":"spid"}]],"inline_keyboard":[[{"text":"fsize","url":"spid"},{"text":"ftype","url":"spid"}]]}' | sed "s|rating|$(echo $info | jq -r '.rating')|g" | sed "s|width|$(echo $info | jq -r '.width')|g" | sed "s|height|$(echo $info | jq -r '.height')|g" | sed "s|fsize|$SIZE|g" | sed "s|ftype|$(echo $info | jq -r '.file_type')|g" | sed "s|spid|https://chan.sankakucomplex.com/post/show/$(echo $info | jq -r '.id')|g") | cat > /dev/null
+curl -s -A "Chrome" "$(echo $info | jq -r '.preview_url')" -o $CPID_CACHE/preview
+curl -s -X POST https://api.telegram.org/bot$TG_BOT_TOKEN/sendPhoto -F chat_id=$CHAT -F caption="$VERSION$(if [ $NUMBER != '-1' ]; then echo -e "\n$COUNT/$NUMBER"; fi)" -F photo="@$CPID_CACHE/preview" -F reply_markup=$(echo '{"inline_keyboard":[[{"text":"rating","url":"spid"},{"text":"widthxheight","url":"spid"}]],"inline_keyboard":[[{"text":"fsize","url":"spid"},{"text":"ftype","url":"spid"}]]}' | sed "s|rating|$(echo $info | jq -r '.rating')|g" | sed "s|width|$(echo $info | jq -r '.width')|g" | sed "s|height|$(echo $info | jq -r '.height')|g" | sed "s|fsize|$SIZE|g" | sed "s|ftype|$(echo $info | jq -r '.file_type')|g" | sed "s|spid|https://chan.sankakucomplex.com/post/show/$(echo $info | jq -r '.id')|g") | cat > /dev/null
 fi
 fi
 fi
