tools: ibd: General code improvements

diff --git a/tools/ibd b/tools/ibd
--- a/tools/ibd
+++ b/tools/ibd
@@ -25,7 +25,7 @@ then
     exit 1
 fi
 
-ibd_version="3.3"
+ibd_version="3.4"
 ibd_cache="${HOME}/.cache/ibd/${$}"
 ibd_config="${HOME}/.config/ibd"
 
@@ -161,11 +161,6 @@ then
         do
             ibd_filename="${ibd_filepath##*/}"
 
-            if ! [ -f "${ibd_filepath}" ]
-            then
-                continue
-            fi
-
             if grep "${ibd_filename}" "${ibd_dir}/list.txt" > /dev/null
             then
                 continue
@@ -220,13 +215,10 @@ if [ -n "${ibd_download_mode}" ]
 then
     case "${ibd_download_mode}" in
         (encount)
-            ibd_encount=0
         ;;
         (full)
-            ibd_full=0
         ;;
         (repair)
-            ibd_repair=0
         ;;
         (*)
             echo "Unrecognized download mode ${ibd_download_mode}. See '${0} -h'"
@@ -239,10 +231,8 @@ if [ -n "${ibd_md5_mode}" ]
 then
     case "${ibd_md5_mode}" in
         (keep)
-            ibd_keep=0
         ;;
         (skip)
-            ibd_skip=0
         ;;
         (*)
             echo "Unrecognized MD5 checksums mode ${ibd_md5_mode}. See '${0} -h'"
@@ -255,16 +245,12 @@ if [ -n "${ibd_exclude_mode}" ]
 then
     case "${ibd_exclude_mode}" in
         (download)
-            ibd_xdownload=0
         ;;
         (remove)
-            ibd_xremove=0
         ;;
         (reversive)
-            ibd_xreversive=0
         ;;
         (selfremove)
-            ibd_xselfremove=0
         ;;
         (*)
             echo "Unrecognized exclude mode ${ibd_exclude_mode}. See '${0} -h'"
@@ -756,94 +742,97 @@ do
 
         ibd_filename="$(printf "%s" "${ibd_file_url}" | eval ${ibd_ifilename})"
         ibd_md5="$(printf "%s" "${ibd_filename}" | cut -d '.' -f 1)"
-        ibd_continue=1
+        ibd_download=1
+        ibd_exclude=1
 
         if [ -f "${ibd_dir}/${ibd_md5}".* ]
         then
-            if [ -n "${ibd_encount}" ]
-            then
-                break 2
-            elif [ -n "${ibd_full}" ]
-            then
-                if [ "$(md5sum "${ibd_dir}/${ibd_md5}".* | cut -d ' ' -f 1)" = "${ibd_md5}" ]
-                then
-                    ibd_continue=0
-                else
-                    rm -f "${ibd_dir}}/${ibd_md5}".*
+            ibd_download=0
 
-                    if [ -f "${ibd_dir}/failed.txt" ]
+            case "${ibd_download_mode}" in
+                (encount)
+                    break 2
+                ;;
+                (full)
+                    if [ "$(md5sum "${ibd_dir}/${ibd_md5}".* | cut -d ' ' -f 1)" != "${ibd_md5}" ]
                     then
-                        sed -e "s/${ibd_md5}//" -e '/^$/d' -i "${ibd_dir}/failed.txt"
+                        ibd_download=1
+
+                        rm -f "${ibd_dir}}/${ibd_md5}".*
+
+                        if [ -f "${ibd_dir}/failed.txt" ]
+                        then
+                            sed -e "s/${ibd_md5}//" -e '/^$/d' -i "${ibd_dir}/failed.txt"
+                        fi
+
+                        ibd_removed=$((ibd_removed + 1))
                     fi
-
-                    ibd_removed=$((ibd_removed + 1))
-                fi
-            elif [ -n "${ibd_repair}" ]
-            then
-                ibd_continue=0
-
-                if [ -f "${ibd_dir}/failed.txt" ]
-                then
+                ;;
+                (repair)
                     if grep "${ibd_md5}" "${ibd_dir}/failed.txt" > /dev/null
                     then
-                        ibd_continue=1
+                        ibd_download=1
 
                         rm -f "${ibd_dir}/${ibd_md5}".*
                         sed -e "s/${ibd_md5}//" -e '/^$/d' -i "${ibd_dir}/failed.txt"
                         ibd_removed=$((ibd_removed + 1))
                     fi
-                fi
-            else
-                ibd_continue=0
-            fi
+                ;;
+            esac
         fi
 
-        if [ -n "${ibd_exclude_dirs}" ]
-        then
-            for ibd_exclude_dir in ${ibd_exclude_dirs}
-            do
-                if [ -f "${ibd_exclude_dir}/${ibd_md5}".* ]
-                then
-                    if [ -n "${ibd_xdownload}" ] || [ -n "${ibd_xremove}" ]
-                    then
-                        ibd_continue=0
+        for ibd_exclude_dir in ${ibd_exclude_dirs}
+        do
+            if [ -f "${ibd_exclude_dir}/${ibd_md5}".* ]
+            then
+                ibd_exclude=0
 
-                        if [ -n "${ibd_full}" ]
-                        then
-                            if [ "$(md5sum "${ibd_exclude_dir}/${ibd_md5}".* | cut -d ' ' -f 1)" != "${ibd_md5}" ]
-                            then
-                                ibd_continue=1
-
-                                if [ -n "${ibd_xremove}" ]
+                case "${ibd_exclude_mode}" in
+                    (download | remove)
+                        case "${ibd_download_mode}" in
+                            (full)
+                                if [ "$(md5sum "${ibd_exclude_dir}/${ibd_md5}".* | cut -d ' ' -f 1)" != "${ibd_md5}" ]
                                 then
-                                    rm -f "${ibd_exclude_dir}/${ibd_md5}".*
+                                    ibd_exclude=1
 
-                                    if [ -f "${ibd_exclude_dir}/failed.txt" ]
-                                    then
-                                        sed -e "s/${ibd_md5}//" -e '/^$/d' -i "${ibd_exclude_dir}/failed.txt"
-                                    fi
-
-                                    ibd_removed=$((ibd_removed + 1))
-                                fi
-                            fi
-                        else
-                            if [ -f "${ibd_exclude_dir}/failed.txt" ]
-                            then
-                                if grep "${ibd_md5}" "${ibd_exclude_dir}/failed.txt" > /dev/null
-                                then
-                                    ibd_continue=1
-
-                                    if [ -n "${ibd_xremove}" ]
+                                    if [ "${ibd_exclude_mode}" = "remove" ]
                                     then
                                         rm -f "${ibd_exclude_dir}/${ibd_md5}".*
-                                        sed -e "s/${ibd_md5}//" -e '/^$/d' -i "${ibd_exclude_dir}/failed.txt"
+
+                                        if [ -f "${ibd_exclude_dir}/failed.txt" ]
+                                        then
+                                            sed -e "s/${ibd_md5}//" -e '/^$/d' -i "${ibd_exclude_dir}/failed.txt"
+                                        fi
+
                                         ibd_removed=$((ibd_removed + 1))
                                     fi
                                 fi
-                            fi
-                        fi
-                    elif [ -n "${ibd_xreversive}" ]
-                    then
+                            ;;
+                            (repair)
+                                if [ -f "${ibd_exclude_dir}/failed.txt" ]
+                                then
+                                    if grep "${ibd_md5}" "${ibd_exclude_dir}/failed.txt" > /dev/null
+                                    then
+                                        ibd_exclude=1
+
+                                        if [ "${ibd_exclude_mode}" = "remove" ]
+                                        then
+                                            rm -f "${ibd_exclude_dir}/${ibd_md5}".*
+                                            sed -e "s/${ibd_md5}//" -e '/^$/d' -i "${ibd_exclude_dir}/failed.txt"
+                                            ibd_removed=$((ibd_removed + 1))
+                                        fi
+                                    fi
+                                fi
+                            ;;
+                        esac
+                    ;;
+                    (reversive)
+                        case "${ibd_download_mode}" in
+                            (full | repair)
+                                ibd_exclude=1
+                            ;;
+                        esac
+
                         rm -f "${ibd_exclude_dir}/${ibd_md5}".*
 
                         if [ -f "${ibd_exclude_dir}/failed.txt" ]
@@ -852,10 +841,8 @@ do
                         fi
 
                         ibd_removed=$((ibd_removed + 1))
-                    elif [ -n "${ibd_xselfremove}" ]
-                    then
-                        ibd_continue=0
-
+                    ;;
+                    (selfremove)
                         if [ -f "${ibd_dir}/${ibd_md5}".* ]
                         then
                             rm -f "${ibd_dir}/${ibd_md5}".*
@@ -867,14 +854,12 @@ do
 
                             ibd_removed=$((ibd_removed + 1))
                         fi
-                    else
-                        ibd_continue=0
-                    fi
-                fi
-            done
-        fi
+                    ;;
+                esac
+            fi
+        done
 
-        if [ ${ibd_continue} -eq 1 ]
+        if [ ${ibd_download} -eq 1 ] && [ ${ibd_exclude} -eq 1 ]
         then
             curl --max-time ${ibd_download_timeout} \
                 --output "${ibd_dir}/${ibd_filename}" \
@@ -889,33 +874,32 @@ do
 
             if [ -f "${ibd_dir}/${ibd_filename}" ]
             then
-                if [ -n "${ibd_skip}" ]
-                then
-                    ibd_success=$((ibd_success + 1))
-                else
-                    if [ "$(md5sum "${ibd_dir}/${ibd_md5}".* | cut -d ' ' -f 1)" = "${ibd_md5}" ]
-                    then
+                case "${ibd_md5_mode}" in
+                    (skip)
                         ibd_success=$((ibd_success + 1))
-                    else
-                        ibd_failed=$((ibd_failed + 1))
-                        printf "%s\n" "${ibd_md5}" >> "${ibd_dir}/failed.txt"
-
-                        if [ -z "${ibd_keep}" ]
+                    ;;
+                    (*)
+                        if [ "$(md5sum "${ibd_dir}/${ibd_md5}".* | cut -d ' ' -f 1)" != "${ibd_md5}" ]
                         then
-                            rm -f "${ibd_dir}/${ibd_md5}".*
-                            ibd_removed=$((ibd_removed + 1))
+                            ibd_failed=$((ibd_failed + 1))
+                            printf "%s\n" "${ibd_md5}" >> "${ibd_dir}/failed.txt"
+
+                            if [ "${ibd_md5_mode}" = "keep" ]
+                            then
+                                rm -f "${ibd_dir}/${ibd_md5}".*
+                                ibd_removed=$((ibd_removed + 1))
+                            fi
+                        else
+                            ibd_success=$((ibd_success + 1))
                         fi
-                    fi
-                fi
+                    ;;
+                esac
+
+                printf "%s\n" "${ibd_filename}" >> "${ibd_dir}/list.txt"
             else
                 ibd_failed=$((ibd_failed + 1))
                 printf "%s\n" "${ibd_md5}" >> "${ibd_dir}/failed.txt"
             fi
-        fi
-
-        if [ -f "${ibd_dir}/${ibd_filename}" ]
-        then
-            printf "%s\n" "${ibd_filename}" >> "${ibd_dir}/list.txt"
         fi
 
         if [ -z "${ibd_quiet}" ]
@@ -940,13 +924,10 @@ then
     rm -f "${ibd_dir}/failed.txt"
 fi
 
-if [ -n "${ibd_exclude_dirs}" ]
-then
-    for ibd_exclude_dir in ${ibd_exclude_dirs}
-    do
-        if ! [ -s "${ibd_exclude_dirs}/failed.txt" ]
-        then
-            rm -f "${ibd_exclude_dirs}/failed.txt"
-        fi
-    done
-fi
+for ibd_exclude_dir in ${ibd_exclude_dirs}
+do
+    if ! [ -s "${ibd_exclude_dirs}/failed.txt" ]
+    then
+        rm -f "${ibd_exclude_dirs}/failed.txt"
+    fi
+done
