Move all the necessary checks after help

diff --git a/tools/ibd b/tools/ibd
--- a/tools/ibd
+++ b/tools/ibd
@@ -10,21 +10,6 @@
 set -e
 umask 77
 
-for required in base64 cat curl cut date grep jq md5sum mkdir rm sed sha1sum sleep tr
-do
-    if ! command -v ${required} > /dev/null
-    then
-        missing="${missing} ${required}"
-    fi
-done
-
-if [ -n "${missing}" ]
-then
-    echo "Missing dependencies:${missing}" \
-        "\nFor more information follow: https://command-not-found.com/"
-    exit 1
-fi
-
 ibd_version="3.5"
 ibd_cache="${HOME}/.cache/ibd/${$}"
 ibd_config="${HOME}/.config/ibd"
@@ -143,6 +128,21 @@ then
         "\n  sankaku\tSankaku Channel <https://chan.sankakucomplex.com/>" \
         "\n  yandere\tyande.re <https://yande.re/>"
     exit 0
+fi
+
+for required in base64 cat curl cut date grep jq md5sum mkdir rm sed sha1sum sleep tr
+do
+    if ! command -v ${required} > /dev/null
+    then
+        missing="${missing} ${required}"
+    fi
+done
+
+if [ -n "${missing}" ]
+then
+    echo "Missing dependencies:${missing}" \
+        "\nFor more information follow: https://command-not-found.com/"
+    exit 1
 fi
 
 if [ -z "${ibd_dir}" ]
diff --git a/tools/tgbot b/tools/tgbot
--- a/tools/tgbot
+++ b/tools/tgbot
@@ -8,21 +8,6 @@
 set -e
 umask 77
 
-for required in curl mkdir
-do
-    if ! command -v ${required} > /dev/null
-    then
-        missing="${missing} ${required}"
-    fi
-done
-
-if [ -n "${missing}" ]
-then
-    echo "Missing dependencies:${missing}" \
-        "\nFor more information follow: https://command-not-found.com/"
-    exit 1
-fi
-
 tgbot_version="1.4"
 tgbot_config="${HOME}/.config/tgbot"
 tgbot_dfile="${tgbot_config}/config"
@@ -72,6 +57,21 @@ then
         "\n  -t <token>\tSpecify access token" \
         "\n  -j <dir>\tSpecify json directory"
     exit 0
+fi
+
+for required in curl mkdir
+do
+    if ! command -v ${required} > /dev/null
+    then
+        missing="${missing} ${required}"
+    fi
+done
+
+if [ -n "${missing}" ]
+then
+    echo "Missing dependencies:${missing}" \
+        "\nFor more information follow: https://command-not-found.com/"
+    exit 1
 fi
 
 mkdir -p "${tgbot_config}"
diff --git a/tools/tgencode b/tools/tgencode
--- a/tools/tgencode
+++ b/tools/tgencode
@@ -7,21 +7,6 @@
 
 set -e
 
-for required in ffmpeg
-do
-    if ! command -v ${required} > /dev/null
-    then
-        missing="${missing} ${required}"
-    fi
-done
-
-if [ -n "${missing}" ]
-then
-    echo "Missing dependencies:${missing}" \
-        "\nFor more information follow: https://command-not-found.com/"
-    exit 1
-fi
-
 tgencode_version="1.8"
 
 if [ -n "${1}" ]
@@ -71,6 +56,21 @@ then
         "\n  -m\t\tAllow multiple files" \
         "\n  -b\t\tDo not exit on error"
     exit 0
+fi
+
+for required in ffmpeg
+do
+    if ! command -v ${required} > /dev/null
+    then
+        missing="${missing} ${required}"
+    fi
+done
+
+if [ -n "${missing}" ]
+then
+    echo "Missing dependencies:${missing}" \
+        "\nFor more information follow: https://command-not-found.com/"
+    exit 1
 fi
 
 if [ -n "${tgencode_noaudio}" ]
