tools: ibd: Sort image boards in alphabetical order

diff --git a/tools/ibd b/tools/ibd
--- a/tools/ibd
+++ b/tools/ibd
@@ -4,14 +4,14 @@
 # Copyright (C) 2024 Danil Lisin
 #
 # Image Board Downloader
-# Supported image boards: Sankaku Channel, Gelbooru
+# Supported image boards: Gelbooru, Sankaku Channel
 
 . ${0%/*}/../iutils
 
 depends curl jq
 
-ibd_version="1.2"
-ibd_cache="${HOME}/.cache/ibd/$$"
+ibd_version="1.3"
+ibd_cache="${HOME}/.cache/ibd/${$}"
 ibd_config="${HOME}/.config/ibd"
 ibd_erase="\033[K"
 
@@ -150,19 +150,19 @@ then
             "\t-d, --dl-timeout <seconds>\tDownload timeout, default: 24 hours\n" \
             "\t-P, --proxy <address>\t\tUse proxy server\n" \
             "\nSupported image boards:\n" \
-            "\tsankaku\t\t\t\tSankaku Channel\n" \
-            "\tgelbooru\t\t\tGelbooru"
+            "\tgelbooru\t\t\tGelbooru\n" \
+            "\tsankaku\t\t\t\tSankaku Channel"
     exit 0
 fi
 
 if [[ -n "${ibd_image_board}" ]]
 then
     case "${ibd_image_board}" in
-    sankaku)
-        ibd_sankaku=0
-    ;;
     gelbooru)
         ibd_gelbooru=0
+    ;;
+    sankaku)
+        ibd_sankaku=0
     ;;
     *)
         echo "Unrecognized image board: '${ibd_image_board}'. See '${0} --help'"
@@ -172,6 +172,30 @@ then
 else
     echo "No image board specified. See '${0} --help'"
     exit 1
+fi
+
+if [[ -n "${ibd_gelbooru}" ]]
+then
+    ibd_api="https://gelbooru.com"
+
+    if [[ -n "${ibd_auth}" ]]
+    then
+        echo "Gelbooru authorization is not supported yet and is not required"
+        exit 1
+    fi
+
+    ibd_page=0
+    ibd_posts_url="${ibd_api}/index.php"
+    ibd_dfield1="page=dapi"
+    ibd_dfield2="s=post"
+    ibd_dfield3="q=index"
+    ibd_dfield4="json=1"
+    ibd_dlimit="limit"
+    ibd_dpage="pid"
+    ibd_dtags="tags"
+    ibd_condition="has(\"post\")"
+    ibd_iurl=".post[].file_url"
+    ibd_ifilename="cut -d '/' -f 7"
 fi
 
 if [[ -n "${ibd_sankaku}" ]]
@@ -270,30 +294,6 @@ then
     ibd_condition=".[0]|has(\"id\")"
     ibd_iurl=".[].file_url"
     ibd_ifilename="cut -d '?' -f 1 | cut -d '/' -f 7"
-fi
-
-if [[ -n "${ibd_gelbooru}" ]]
-then
-    ibd_api="https://gelbooru.com"
-
-    if [[ -n "${ibd_auth}" ]]
-    then
-        echo "Gelbooru authorization is not supported yet and is not required"
-        exit 1
-    fi
-
-    ibd_page=0
-    ibd_posts_url="${ibd_api}/index.php"
-    ibd_dfield1="page=dapi"
-    ibd_dfield2="s=post"
-    ibd_dfield3="q=index"
-    ibd_dfield4="json=1"
-    ibd_dlimit="limit"
-    ibd_dpage="pid"
-    ibd_dtags="tags"
-    ibd_condition="has(\"post\")"
-    ibd_iurl=".post[].file_url"
-    ibd_ifilename="cut -d '/' -f 7"
 fi
 
 if [[ -z "${ibd_dir}" ]]
