tools: ibd: Add yande.re support

diff --git a/tools/ibd b/tools/ibd
--- a/tools/ibd
+++ b/tools/ibd
@@ -4,13 +4,13 @@
 # Copyright (C) 2024 Danil Lisin
 #
 # Image Board Downloader
-# Supported image boards: Gelbooru, Sankaku Channel
+# Supported image boards: Gelbooru, Sankaku Channel, yande.re
 
 . ${0%/*}/../iutils
 
 depends curl jq
 
-ibd_version="1.3"
+ibd_version="1.4"
 ibd_cache="${HOME}/.cache/ibd/${$}"
 ibd_config="${HOME}/.config/ibd"
 ibd_erase="\033[K"
@@ -151,7 +151,8 @@ then
             "\t-P, --proxy <address>\t\tUse proxy server\n" \
             "\nSupported image boards:\n" \
             "\tgelbooru\t\t\tGelbooru\n" \
-            "\tsankaku\t\t\t\tSankaku Channel"
+            "\tsankaku\t\t\t\tSankaku Channel\n" \
+            "\tyandere\t\t\t\tyande.re"
     exit 0
 fi
 
@@ -163,6 +164,9 @@ then
     ;;
     sankaku)
         ibd_sankaku=0
+    ;;
+    yandere)
+        ibd_yandere=0
     ;;
     *)
         echo "Unrecognized image board: '${ibd_image_board}'. See '${0} --help'"
@@ -294,6 +298,26 @@ then
     ibd_condition=".[0]|has(\"id\")"
     ibd_iurl=".[].file_url"
     ibd_ifilename="cut -d '?' -f 1 | cut -d '/' -f 7"
+fi
+
+if [[ -n "${ibd_yandere}" ]]
+then
+    ibd_api="https://yande.re"
+
+    if [[ -n "${ibd_auth}" ]]
+    then
+        echo "yande.re authorization is not supported yet and is not required"
+        exit 1
+    fi
+
+    ibd_page=1
+    ibd_posts_url="${ibd_api}/post.json"
+    ibd_dlimit="limit"
+    ibd_dpage="page"
+    ibd_dtags="tags"
+    ibd_condition=".[0]|has(\"id\")"
+    ibd_iurl=".[].file_url"
+    ibd_ifilename="sed 's/\/yande.re.*\./\./' | cut -d '/' -f 5"
 fi
 
 if [[ -z "${ibd_dir}" ]]
