tools: tgencode: Add similar to ibd dependencies check

diff --git a/tools/tgencode b/tools/tgencode
--- a/tools/tgencode
+++ b/tools/tgencode
@@ -3,10 +3,23 @@
 # Copyright (C) 2024 Maria Lisina
 #
 # Reencode media to optimize playback in Telegram
-#
-# Prerequisites: ffmpeg
 
 set -e
+
+for required in ffmpeg
+do
+    if ! command -v ${required} > /dev/null
+    then
+        missing="${missing} ${required}"
+    fi
+done
+
+if [ -n "${missing}" ]
+then
+    echo "Missing dependencies:${missing}\n" \
+        "For more information follow: https://command-not-found.com/"
+    exit 1
+fi
 
 if [ -z "${1}" ]
 then
